### ISSUE TITLE
Error: 1: list index out of range | 2: list index out of range when trying playing podcast.

### ISSUE THREAD

**Issue by Bruno21** [avantrec/soco-cli#1]
First, thanks for this wonderful tool. I've added several alias in my .zshrc to quickly control my Sonos One.

I've added a podcast (French podcast: Le moment Meurice) from the Pocket Casts app in my fav list:

```
❯ sonos Salon list_favs

    1: Flow, votre mix personnalisé (Deezer)
    2: France Inter 95.9 (Émissions-débats France)
    3: K6 FM 101.6 (Musique Locale)
    4: Le moment Meurice
```

I get this error when I try to play the podcast:
```
❯ sonos Salon play_fav 'Le moment Meurice'
Error: 1: list index out of range | 2: list index out of range

❯ sonos Salon play_fav "Meurice"
Error: 1: list index out of range | 2: list index out of range
```

Maybe there is another way to play podcasts from solo-cli ?

Edit: try adding the podcast from TuneIn, same error.

**Comment by pwt** [comment]
Thanks for your comment ... glad you're finding it useful.

The short answer is that this currently works for **individual** Pocket Casts podcast episodes added to the Sonos Favourites list, but not if one adds a whole podcast series.

This is true from the Sonos app, too. If you have a Pocket Casts podcast series in the Sonos Favourites, it can't be played directly -- you have to click into the series and choose the episode(s) to be played.

I'll take look to see if I can work around this somehow; I can see how it would be useful just to play whatever's in the current episode list for a podcast series. In general, I'd like better support for music services like Pocket Casts, but this depends on SoCo figuring out how to expose these capabilities.

**Comment by Bruno21** [comment]
Thanks for your answer. Keep up the good work !

**Comment by pwt** [comment]
I've done some experimentation with this -- looking at WireShark traces from the Sonos app, etc. -- and I can't find any 'quick and dirty' way to make it work. I think SoCo will need better music service support, or it's possible I'm misunderstanding something.

In the meantime, we're left with the workarounds:

- Add single episodes to the Sonos Favourites list, and play these directly using `play_fav`
- Add multiple episodes to a Sonos Playlist, and play these using `apq` and `pfq`

Clearly, neither of these has the desirable property of just playing the latest podcast(s) in the list. As a heavy Pocket Casts user myself, I really like the idea of this, so I'll keep thinking about it in the background.
