### ISSUE TITLE
Saved History not working

### ISSUE THREAD

**Issue by naxels** [avantrec/soco-cli#11]
Was just testing the new version 0.3.8, installed through pip.

For some reason, I don't get an error, however the command line history save is not working.

I'm using Python 3.9.1 on a MacBook Pro running Big Sur.

While browsing through the commit/code I couldn't really figure out why.

After some more testing, this is what finally got it to work as expected:

In a Terminal, type:
`cd ~`
`mkdir .soco-cli`

Then from that moment on, sonos will create and append/save to the file shell-history.txt.

Maybe a Python command needs to be added to create this directory in case it doesn't exist?

Keep up the good work :)

**Comment by pwt** [comment]
Good catch.

A couple of existing functions use the `.soco-cli` directory, so all of my test systems already had it created. Will fix in the next version.

**Comment by pwt** [comment]
Fixed in 0.3.9.
