### ISSUE TITLE
Feature request - always action request on coordinator

### ISSUE THREAD

**Issue by rleeden** [avantrec/soco-cli#13]
Hi,

I have a suggestion for a slight change in behaviour:

Often I will want to perform an action - say 'pause' on a particular speaker that I am listening to - say 'kitchen'.

So I run 'sonos -l kitchen pause', only to be told that kitchen is not the coordinator. I then have to figure out which speaker is the coordinator and run the same command on the correct speaker. I was wondering if your script could figure this out for me? I want to pause the music in the group that 'kitchen' is part of, but I don't really care who the coordinator is - I just want the music paused.

I'm not sure if there are disadvantges to this approach, but it seems it could be useful? 

Richard

**Comment by pwt** [comment]
This is a good idea. (I don't use groups much so it's not something that had occurred to me.)

For a specific subset of SoCo-CLI actions, it's simply necessary to divert the action to the group coordinator, which requires a bit of modest code refactoring. There's quite a broad range of actions to which this could/should apply. I think I've addressed most of them in the v0.3.16 release, but I might either have missed some or indeed been overzealous.

Let me know of any issues!
