### ISSUE TITLE
"Error: 'NoneType' object is not iterable" using sonos-discover

### ISSUE THREAD

**Issue by prasket** [avantrec/soco-cli#18]
Hello Team! 

I am getting the following error while trying to utilize sonos-discover to use soco-cli.

**Error: 'NoneType' object is not iterable**

```bash
(soco-cli)  ~/projects/temp/soco-cli$ sonos-discover -t 256 -n 1.0 -m 16
Error: 'NoneType' object is not iterable

(soco-cli)  ~/projects/temp/soco-cli$ sonos-discover
Error: 'NoneType' object is not iterable
```

On the first command I was using -m 16 due to my sonos devices being on a different vlan than my computer. I was not able to find a way to manually create a cached set of devices to use in soco-cli. 

I setup my env the following way

```bash
pipenv install --python 3
pipevn shell
pipenv install soco-cli
```

Python = Python 3.8.6
OS = POP_OS 20.10 

What else can I provide or dig into looking at this?

**Comment by pwt** [comment]
Hi:

Could you provide the output of the following commands, please?

1. `sonos -v`
2. `sonos-discover -t 256 -n 1.0 -m 16 --log=info`

Thanks.

**Comment by pwt** [comment]
I think I know where the exception arises, and I've addressed this in v0.3.30 by providing a more meaningful error message, namely `No speakers discovered. No cache data saved or overwritten.`

However, this doesn't address your root problem, which is that no devices are found by the network search. Are you sure the speaker IPs are reachable from the computer on which you're running SoCo-CLI?

Please do still provide the outputs (1) and (2) requested above; it will tell us what networks are discovered and searched. Thanks.

**Comment by prasket** [comment]
Hi @pwt 
Here is the info you asked for

```bash
(soco-cli)  ~/projects/temp/soco-cli$ sonos -v
soco-cli version: 0.3.29
soco version:     0.21.3
python version:   3.8.6
```

```bash
(soco-cli)  ~/projects/temp/soco-cli$ sonos-discover -t 256 -n 1.0 -m 16 --log=info
2021-04-03 14:37:11,006 discovery.py:550 - _find_ipv4_networks() - Set of networks to search: {IPv4Network('192.168.2.0/24')}
2021-04-03 14:37:11,032 discovery.py:335 - scan_network() - Created 256 scanner threads
2021-04-03 14:37:12,033 discovery.py:340 - scan_network() - All 256 scanner threads terminated
2021-04-03 14:37:12,033 discovery.py:344 - scan_network() - No Sonos zones discovered
Error: 'NoneType' object is not iterable
```

I noticed with the log info that it does not seem to be pulling in the cider from -m flag. That might be why it cannot see the devices on 192.168.70.* network which is where my sonos system lives. 

I installed the socos library and when I pass in the IP of one of my devices it returns. 

```bash
(socos)  ~/projects/temp/socos$ socos info 192.168.70.45
zone_name: Office
zone_icon: 
uid: None
serial_number: REDACTED
software_version: 62.1-86220
hardware_version: 1.23.1.10-1.1
mac_address: REDACTED
```
I was also able to get the track info using a python script and soco that I passed in the IP.

```python
#!/usr/bin/env python3
from soco import SoCo
from pprint import pprint

if __name__ == '__main__':
    device = SoCo('192.168.70.45') # Pass in the IP of your Sonos speaker
    track = device.get_current_track_info()
    print(f"Now Playing {track['title']} By  {track['artist']}")
```
```bash
(soco)  ~/projects/temp/soco$ python track.py 
Now Playing Stupid Minds (Polished Chrome Remix) By  Sine
```

I understand networking troubleshooting can be painful, is there a work around I could use. Maybe creating my own cached discovery list file and using the `-l` flag when running?

**Comment by pwt** [comment]
Great, thanks for the info.

Interesting use case; the first example reported where the Sonos speakers reside on a different subnet from the controlling device. Fortunately, when I wrote the recent discovery code in the SoCo library, I included the ability to specify which subnets to search, to override the networks determined from interface inspection.

In **SoCo-CLI v0.3.32** (available now), I've added a `--subnets` option to `sonos-discover`. In your case you should be able to use: **`sonos-discover --subnets 192.168.70.0/24`** to discover your speakers and cache the results. Let me know if this works.

(You could probably also just specify the IP address of *one* of your speakers, if you know it, and the others will be discovered too: **`sonos-discover --subnets 192.168.70.45`**.)

Incidentally, you can always use IP addresses directly with SoCo-CLI if you want to, e.g.: **`sonos 192.168.70.45 info`**.

Finally, for completeness, the **`-m`** option will only ever constrain the netmask, never increase it. It's there to control the size of the search space.

**Comment by pwt** [comment]
I'm going to close this issue now. Please reopen if your issue is not resolved.
