### ISSUE TITLE
Sonos Controls from Raspberry Pi

### ISSUE THREAD

**Issue by zubairqureshi81** [avantrec/soco-cli#23]
Hello,

I am trying to control Sonos from Raspberry Pi. I am able to control the volume but not other functions. Not sure what I am missing.
I am trying to control status lights, switch the Sonos connect (named Office) to line-in and also select (everywhere) from the group to play music to all speakers.

Below is my script:

-----------------------------------------------------
import soco
from soco from SoCo
from soco_cli import api
from soco_cli import action_processor as ap
from soco_cli.api import run_command

Office = SoCo('172.17.16.133')
Office.volume = 10
Office.status_light = 'on'
Office.line_in = 'switch_to_line_in'
-----------------------------------------------------

Can you please help with this?

**Comment by pwt** [comment]
If you have SoCo-CLI installed, you don't need to write any Python. Instead, from the terminal command line (or from a shell script):
```
$ sonos Office volume 10
$ sonos Office status_light on
$ sonos Office line_in on
```
Or, as a single sequence of commands:
```
$ sonos Office volume 10 : Office status_light on : Office line_in on
```
To group all speakers in your system:
```
$ sonos Office party_mode
```
Let me know if this answers your question.

**Comment by zubairqureshi81** [comment]
I tried this but after installing SoCo-CLI (this is how I installed it "pip install -U soco-cli"), I do not get the option to type sonos in terminal. Not sure if there is any other step in between that I am missing?

pi@raspberrypi:~$ sonos Office volume 10
bash: sonos: command not found
pi@raspberrypi:~$

**Comment by pwt** [comment]
Sounds like you might not be in the right Python environment? What's the output given by:
`which python` and  `pip freeze`?

**Comment by zubairqureshi81** [comment]
Thank you for the prompt response and help. Here's the output below:

pi@raspberrypi:$ which python and pip freeze
/usr/bin/python
/usr/bin/pip
pi@raspberrypi:$

**Comment by pwt** [comment]
Thanks. My instructions could have been clearer: could I get the output of `pip freeze` run as a single command, please?

**Comment by zubairqureshi81** [comment]
Sorry about that....here you go....attached is the output

[pip freeze run.txt](https://github.com/avantrec/soco-cli/files/7590071/pip.freeze.run.txt)

**Comment by pwt** [comment]
Thanks.

Well, that's odd. SoCo-CLI is installed in your default/system Python environment (which is what you're using).

Could you let me have the output of the following two commands, please:
```
echo $PATH
```
and
```
python --version
``` 
Thanks.

**Comment by zubairqureshi81** [comment]
Yes, here you go.

pi@raspberrypi:~ $ echo $PATH
/home/pi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games

pi@raspberrypi:~ $ python --version
Python 3.9.2
pi@raspberrypi:~ $

**Comment by zubairqureshi81** [comment]
I had to define the path and it started working after that. I will do few more tests and let you know if I need any more help.
Thanks again for pointing me to the right direction.

pi@raspberrypi:~ $ export PATH=/home/pi/.local/bin:$PATH
pi@raspberrypi:~ $ echo $PATH
/home/pi/.local/bin:/home/pi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games

**Comment by pwt** [comment]
Great -- well done.

Python is usually run from within a virtual environment, in which case the PATH is set up appropriately when a given venv is activated.

In the case where the system Python is being used, PATH obviously has to be set up manually. Haven't come across this before; I'll add a note to the README.
