### ISSUE TITLE
audio_format giving error

### ISSUE THREAD

**Issue by rleeden** [avantrec/soco-cli#26]
Hi,

I am getting an error with the new audio_format action. Error is:

`Error: 'SoCo' object has no attribute 'audio_input_format'`

I think it's a simple typo at line 3259 of action_processor.py, which should be calling the soco function 'soundbar_audio_input_format' rather than 'audio_input_format'

For info my versions are:

sonos --version
soco-cli version: 0.4.28
soco version:     0.25.2
python version:   3.10.1

**Comment by pwt** [comment]
Thanks for catching this. I'm a bit exposed on the home theatre actions because I don't have a set up to test with. At some point I'll hook up my Amp to a TV, but that requires a new TV.

Should be fixed in v0.4.29 (released).
