### ISSUE TITLE
Feature Request - Define subnet/use local cache for soco-http-api-server

### ISSUE THREAD

**Issue by AlexLamond** [avantrec/soco-cli#31]
Based on the API documentation, it is not possible to tell the HTTP API to use the list of cached objects or use a specific subnet. Can you clarify this is the case/consider adding this feature?

**Comment by pwt** [comment]
Hi @AlexLamond : I dithered over whether to allow use of cached speaker data, or whether to allow the search subnet to be passed as a parameter. It's not currently possible, but it should be easy to add -- so I'll do so.

**Comment by pwt** [comment]
I've now added this option in **v0.4.45**: https://github.com/avantrec/soco-cli#using-the-local-speaker-cache.

As always, let me know if you encounter any issues, or if the documentation is unclear.

**Comment by pwt** [comment]
Hi @AlexLamond -- I'm going to close this issue now. Feel free to reopen if you need to.

(I'm aware that there's a minor bug in v0.4.45 using the `/speakers` endpoint with the local cache. This is fixed in the next release.)
