### ISSUE TITLE
Action 'play_file' does not work with AAC files

### ISSUE THREAD

**Issue by pwt** [avantrec/soco-cli#4]
AAC and WMA files are supported for playback by Sonos, but don't currently work with the `play_file` action. Needs investigation.

https://developer.sonos.com/build/content-service-add-features/supported-audio-formats/

**Comment by pwt** [comment]
**v0.1.48** has partial support for AAC files.

Basic playback works well, but there's no display of metadata or album art, and no ability to seek within the track. This is because AAC files have to be treated like streaming radio to get Sonos to play them.

**Comment by pwt** [comment]
**v0.1.48** also adds support for WMA files.

For some reason the sample WMA file I'd been using would not play on Sonos, with the error "the file is in an unsupported format". I tried an alternative sample file (http://www.theflute.co.uk/media/BachCPE_SonataAmin_1.wma), and this played fine.

So, I'm uncertain about how robust WMA playback is because I don't have a library of WMA files, but I'm going to close this issue as I think I've done what I can from a SoCo-CLI perspective.

**Comment by pwt** [comment]
AAC file playback is very unstable. Mostly works on macOS, but not on Linux or Windows. I'm investigating why there are differences.

**Comment by pwt** [comment]
See associated SoCo question: https://github.com/SoCo/SoCo/issues/783.

**Comment by avantrec** [comment]
Closing: won't fix.
