### ISSUE TITLE
Adjust line-in delay

### ISSUE THREAD

**Issue by pascalpfeil** [avantrec/soco-cli#41]
The sonos app can adjust the line-in delay, can this be added to the cli?

![vinyl-on-sonos-speakers-inline-1617128996](https://user-images.githubusercontent.com/8393532/192111741-3d0f4f28-614e-4a49-9a2c-3ff39a4456e4.jpg)

**Comment by pwt** [comment]
Just to check: are you sure you're not looking for TV audio delay adjustment (for lip-sync)?

If so, there's the existing `tv_audio_delay` action for that.

**Comment by pascalpfeil** [comment]
Yeah I saw that, that does stuff for soundbars. I am trying to get rid of the line-in delay on my Play:5 Gen 1.

**Comment by pwt** [comment]
OK.

Note that you can't get rid of the Line In delay completely; it's a minimum of 75ms even when a device is playing from its own Line In. There's no way around this.

I can take a look at adding the available options to SoCo-CLI. It'll need to be added to SoCo first.

**Comment by pascalpfeil** [comment]
75ms would be awesome! I am currently on 2s, and the speaker won't connect to the app any more to change it (I don't know why). I can control it via this tool, however.

**Comment by pascalpfeil** [comment]
Any progress? Let me know if I can assist you with anything :)

**Comment by pwt** [comment]
Don't expect rapid progress on this. The Sonos API call for managing this setting isn't found anywhere obvious (I've looked), so some investigation will be required to figure out how to access it.

**Comment by pascalpfeil** [comment]
I see, thanks!

**Comment by pascalpfeil** [comment]
A month has passed, anything I can do to speed this up? :)

**Comment by pwt** [comment]
> A month has passed, anything I can do to speed this up? :)

Not really, unless you have a way of tapping into the protocol exchange between the Sonos app. and the speaker when this function is invoked from the app.

**Comment by pascalpfeil** [comment]
Unfortunately, due to reasons unknown to me, my speaker won't work with the app any more... Guess I'll just have to wait, thanks

**Comment by pwt** [comment]
Using `rvictl` from Xcode on macOS, I managed to enable WireShark to snoop on the packets sent between the Sonos App on my iPhone and a Sonos speaker when changing the Line In Audio Delay.

See https://medium.com/geekculture/capture-iphone-ios-http-traffic-using-wireshark-4af01a4313e6 for details of the approach.

Unfortunately, the Line In Delay setting uses an encrypted message exchange -- HTTPS (I assume) over port 1443 on the Sonos device -- so we don't currently have a way of controlling this via SoCo. The screenshot shows the network traffic for two operations to change the delay.

![screenshot_0286](https://user-images.githubusercontent.com/1089749/201523585-8eae7bda-701f-4aa7-a870-898131997d0e.png)

Hence I'm going to close this issue. Apologies that we're not presently able to support this.

**Comment by pascalpfeil** [comment]
Thanks @pwt for trying! That's really unfortunate - if you ever come across a method to adjust the delay, please let me know.
