### ISSUE TITLE
Take what is currently playing on Mac and play on Sonos

### ISSUE THREAD

**Issue by deverman** [avantrec/soco-cli#52]
Hi I was wondering if it is possible to basically replicate selecting the Sonos as an airplay speaker and playing the current Mac audio to it?  Wanted to say auto move the current movie audio I'm watching on Netflix on my Mac over to my Sonos speakers with the press of a button on my stream deck. Anyway to do this?

**Comment by pwt** [comment]
Sorry, not something that SoCo-CLI can do.
Might be worth exploring whether macOS Shortcuts might be able to do this.
