### ISSUE TITLE
Problems with deleting playlists

### ISSUE THREAD

**Issue by vbonline** [avantrec/soco-cli#53]
Hi, 

I'm a but stumped... 
Not sure if I'm using it wrong or if I found an error...

soco lp (list playlists):
 1: 1 - Pop l
    --- snipp ---
   19: WW II - The Pacific
   20: xxx
So there is a playlist named xxx:

soco delete_playlist xxx
Error: Playlist 'xxx' not found. 

This should work, right?

Debug output is attached...
[error.txt](https://github.com/avantrec/soco-cli/files/11021173/error.txt)

**Comment by pwt** [comment]
Thanks for finding and reporting this bug.
It should be fixed in v0.4.60. Please give it a try when you get a chance.

**Comment by vbonline** [comment]
Nice! works like a charm (now)...
:-)

Thanks for the fix!
