### ISSUE TITLE
Can't seem to play RTSP stream created by Audio Sharing

### ISSUE THREAD

**Issue by drgnomage** [avantrec/soco-cli#55]
When I try to share the audio from my linux laptop using the [Audio Sharing](https://flathub.org/apps/de.haeckerfelix.AudioSharing) program, I get a notification that there is a device connecting to the audio stream but then the state of the speaker is STOPPED.

I've tried a couple of different ways of sending the stream:
> play_uri "rtsp://192.168.xxx.xxx:8554/audio"
> play_uri "x-rincon-mp3radio://192.168.xxx.xxx:8554/audio"

I've disabled firewalld and I'm getting the connected notification so I know networking isn't an issue.

There is no error that I can see so I'm a little stumped.

**Comment by pwt** [comment]
Looks like Sonos only supports RTSP when using the WMA format [1]. What format is Audio Sharing using?

[1] https://developer.sonos.com/build/content-service-add-features/supported-audio-formats

**Comment by pwt** [comment]
Thanks. As per the Sonos link, it appears that Sonos devices will only play Ogg Vorbis when streamed over HTTP/S.

You may want to contact the author of Audio Sharing to see if it's possible to stream in a different encoding format, or use a different streaming protocol.

**Comment by drgnomage** [comment]
Cheers for looking into it @pwt!

I'll reference these issues to each other, just in case someone else wants the same thing.

> https://gitlab.gnome.org/World/AudioSharing/-/issues/19
