### ISSUE TITLE
What is the "local library"?

### ISSUE THREAD

**Issue by RanTalbott** [avantrec/soco-cli#62]
The README makes references to a "local library" as distinct from the "Sonos library". Is this something created on the local filesystem by the Sonos software?

I'm a Linux user, and thought (mistakenly, apparently) that it referred to my filesystem, but I get "not found" errors when I try to use local files as track and playlist names.

**Comment by pwt** [comment]
https://support.sonos.com/en-gb/article/add-your-music-library-to-sonos
