### ISSUE TITLE
Error message when queueing URIs

### ISSUE THREAD

**Issue by RanTalbott** [avantrec/soco-cli#64]
I have my fileserver and filename-to-URI translator working. Adding URIs to the queue works, except that, when loading to an empty queue, the first URI winds up at the end, with the others being loaded in the correct sequence ahead of it. Should I always force the fueue position instead of "next"? That worked to get them in order, and I can do a little scripting to retrieve the queue and figure out the right numbers.  Meanwhile, at every invocation of sonos add_uri_to_queue, I get one of these error messages. If you let me know where you think they might originate, I can add some debugging code to try to find the cause.

ran@delve:trackserver$ for i in `cat cs_uris`;do sonos add_uri_to_queue $i next;done
<function zero_parameters.<locals>.wrapper at 0x7fe2a85809d0>
<function zero_parameters.<locals>.wrapper at 0x7f787d97b9d0>
<function zero_parameters.<locals>.wrapper at 0x7f7966cd9a60>
<function zero_parameters.<locals>.wrapper at 0x7ff2d9330a60>
<function zero_parameters.<locals>.wrapper at 0x7f8b053c99d0>
<function zero_parameters.<locals>.wrapper at 0x7f09344039d0>
<function zero_parameters.<locals>.wrapper at 0x7f45a108e9d0>
<function zero_parameters.<locals>.wrapper at 0x7f115cb779d0>
<function zero_parameters.<locals>.wrapper at 0x7fb2ec2f09d0>
<function zero_parameters.<locals>.wrapper at 0x7faf7d4269d0>
<function zero_parameters.<locals>.wrapper at 0x7f5164c47a60>
<function zero_parameters.<locals>.wrapper at 0x7f7e9368aa60>

Here are the URIs. I don't see anything odd about them. Maybe the numeric IP address instead of a host name??
[cs_uris.txt](https://github.com/avantrec/soco-cli/files/12844712/cs_uris.txt)

**Comment by pwt** [comment]
> Adding URIs to the queue works, except that, when loading to an empty queue, the first URI winds up at the end, with the others being loaded in the correct sequence ahead of it. Should I always force the fueue position instead of "next"? That worked to get them in order, and I can do a little scripting to retrieve the queue and figure out the right numbers

If you use the action `add_uri_to_queue` without any positional arguments (i.e., without a `<queue_position or next>` argument), each track should be added to the end of the queue in sequence.

**Comment by pwt** [comment]
> `<function zero_parameters..wrapper at 0x7fe2a85809d0>`

Looks like that's a bug on my part. Fix should be simple.

**Comment by pwt** [comment]
Should be fixed in v0.4.71. Please check and confirm. Thanks.

**Comment by RanTalbott** [comment]
That fixed it. Thanks.

The README gives the impression that a number/next is a required parameter. Maybe use square brackets to identify optional stuff? That's a convention that CLI users are accustomed to.

**Comment by pwt** [comment]
> The README gives the impression that a number/next is a required parameter. Maybe use square brackets to identify optional stuff? That's a convention that CLI users are accustomed to.

The behaviour is fully described at the start of the [Queue Actions](https://github.com/avantrec/soco-cli#queue-actions) section.
