### ISSUE TITLE
URL with Macro argument

### ISSUE THREAD

**Issue by jeantristan** [avantrec/soco-cli#72]
Hi there,

I just discovered this fantastic tool.

The following commands are working:
```
sonos Chambre sharelink "https://open.spotify.com/track/6cpcorzV5cmVjBsuAXq4wD" start
sonos Chambre play_from_queue 1
```

Then I put this commands into a macro. It's working with
`play_chambre = Chambre sharelink "https://open.spotify.com/track/6cpcorzV5cmVjBsuAXq4wD" start : Chambre play_from_queue 1`

Then I tried to add an argument into the URL provided using:
`play_chambre = Chambre sharelink %1 start : Chambre play_from_queue 1`

When I tried: `http://192.168.1.83:8000/macro/play_chambre/https://open.spotify.com/intl-fr/album/4V9BgSnwEMP5yRnZE5flSP`
It's not working. I also tried to URL encode the spotify link. It's not working either.

Do you have any idea?

**Comment by pwt** [comment]
Hi. This is somewhat tricky to solve in its full generality, but v0.4.76 adds a `play_sharelink` action that appends a sharelink to the end of the queue **and** starts playback. This may provide you with what you need -- i.e., you can use:

`http://192.168.1.83:8000/Chambre/play_sharelink/https://open.spotify.com/intl-fr/album/4V9BgSnwEMP5yRnZE5flSP`

Let me know if this helps.

**Comment by jeantristan** [comment]
Thanks for your answer, that was exactly what I was looking for.
