### ISSUE TITLE
HTTP API Server + (async) play_dir = error when trying to play a second dir

### ISSUE THREAD

**Issue by davidbgk** [avantrec/soco-cli#76]
Hey there,

Thanks to the latest iOS version of the official SONOS app (ahem), I'm trying to make a web interface to soco-cli using the built-in API server and so far so good for my usage:

![14C38257-F647-4C54-B816-8EAFC481706C_4_5005_c](https://github.com/avantrec/soco-cli/assets/3556/e2c487e8-31a2-440f-8b72-919fe2f5d7ce)

I'm retrieving the volume from speakers and I'm able to launch a directory full of flac music from my local library (yay!).

But, when I'm hitting `async_play_dir` for the second time, the first one is not cancelled even if I paused the speaker.

I guess it's because the `play_dir` action [is launched as a subprocess](https://github.com/avantrec/soco-cli/blob/29b716dd01e96899ee57a2d2fdf0f8307bcd6c27/soco_cli/http_api.py#L67) and the pid is not kept to be killed once the custom server need to be ended.

@pwt do you have the same interpretation? I know the async feature is quite recent but it actually doesn't work either with the sync call. I guess the json response should return the pid of the process to be killed or the server should keep it in memory to be able to stop it prior to be able to play another directory. I'm willing to initiate a PR with some guidance (and open-source that frontend at some point).

**Comment by davidbgk** [comment]
If I understand correctly, the special `_end_on_pause_` for `play_file` could be extended to `play_directory` and then follow `play_directory_files -> play_file_list -> play_local_file` with the regular `end_on_pause` parameter. `wait_until_stopped` would then hopefully take that into account. 🤔

**Comment by davidbgk** [comment]
Even forcing `end_on_pause` to `True` at the `wait_until_stopped` level doesn't look to work, I should miss something.

**Comment by pwt** [comment]
Hi @davidbgk 

Thanks for your interest in SoCo-CLI.

I didn't really anticipate the HTTP API server functionality being used much for long-running actions, so we're finding some new requirements, which is always interesting.

I've just released v0.4.78, which imposes mutual exclusion for `async` actions on a given speaker. In other words, any currently running `async` action will be cancelled if a new `aysnc` action arrives for the same speaker. It uses the method you suggest: keeping track of subprocess PIDs. Note that a new **non-async** action will not cancel a running `async` action.

This should give you the behaviour you want, although I still consider this area to be experimental. Let me know how you get on.

The `_end_on_pause_` option now works for `play_file` when invoked via the HTTP API server, but it's never been supported with `play_dir`.

**Comment by davidbgk** [comment]
@pwt this is awesome! Thank you so much for your reactivity and reading the commits helps me better understand the logic behind 🙇 

I confirm that it works as expected now with no ghost process trying to play multiple albums at a time on the same speaker.
